/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { StatusEnum } from './status-enum';
 /**
 * 
 *
 * @export
 * @interface SysCategory
 */
export interface SysCategory {

    /**
     * 雪花Id
     *
     * @type {number}
     * @memberof SysCategory
     */
    id?: number;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof SysCategory
     */
    createTime?: Date;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof SysCategory
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof SysCategory
     */
    createUserId?: number | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof SysCategory
     */
    createUserName?: string | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof SysCategory
     */
    updateUserId?: number | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof SysCategory
     */
    updateUserName?: string | null;

    /**
     * 软删除
     *
     * @type {boolean}
     * @memberof SysCategory
     */
    isDelete?: boolean;

    /**
     * 租户Id
     *
     * @type {number}
     * @memberof SysCategory
     */
    tenantId?: number | null;

    /**
     * 父Id
     *
     * @type {number}
     * @memberof SysCategory
     */
    pid?: number;

    /**
     * 编码
     *
     * @type {string}
     * @memberof SysCategory
     */
    code?: string | null;

    /**
     * 级别
     *
     * @type {number}
     * @memberof SysCategory
     */
    level?: number | null;

    /**
     * 排序
     *
     * @type {number}
     * @memberof SysCategory
     */
    orderNo?: number;

    /**
     * @type {StatusEnum}
     * @memberof SysCategory
     */
    status?: StatusEnum;

    /**
     * 备注
     *
     * @type {string}
     * @memberof SysCategory
     */
    remark?: string | null;

    /**
     * 分类子项
     *
     * @type {Array<SysCategory>}
     * @memberof SysCategory
     */
    children?: Array<SysCategory> | null;

    /**
     * 是否禁止选中
     *
     * @type {boolean}
     * @memberof SysCategory
     */
    disabled?: boolean;

    /**
     * 名称
     *
     * @type {string}
     * @memberof SysCategory
     */
    name?: string | null;

    /**
     * 分类类型
     *
     * @type {string}
     * @memberof SysCategory
     */
    type?: string | null;

    /**
     * 描述
     *
     * @type {string}
     * @memberof SysCategory
     */
    description?: string | null;
}