//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSD.Reinforcement.Engine.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.35")]
        public double FactorOfDeadLoad {
            get {
                return ((double)(this["FactorOfDeadLoad"]));
            }
            set {
                this["FactorOfDeadLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9.8")]
        public double VolumetricWeightOfWater {
            get {
                return ((double)(this["VolumetricWeightOfWater"]));
            }
            set {
                this["VolumetricWeightOfWater"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public double VolumetricWeightOfSoil {
            get {
                return ((double)(this["VolumetricWeightOfSoil"]));
            }
            set {
                this["VolumetricWeightOfSoil"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double Surcharge {
            get {
                return ((double)(this["Surcharge"]));
            }
            set {
                this["Surcharge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.13")]
        public double MinSteelRatio {
            get {
                return ((double)(this["MinSteelRatio"]));
            }
            set {
                this["MinSteelRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double MaxSteelRatio {
            get {
                return ((double)(this["MaxSteelRatio"]));
            }
            set {
                this["MaxSteelRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double AnagleOfResistance {
            get {
                return ((double)(this["AnagleOfResistance"]));
            }
            set {
                this["AnagleOfResistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public double FactorOfImposedLoad {
            get {
                return ((double)(this["FactorOfImposedLoad"]));
            }
            set {
                this["FactorOfImposedLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public double FactorOfLiveLoad {
            get {
                return ((double)(this["FactorOfLiveLoad"]));
            }
            set {
                this["FactorOfLiveLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19")]
        public double SaturatedDensityForFillingMaterials {
            get {
                return ((double)(this["SaturatedDensityForFillingMaterials"]));
            }
            set {
                this["SaturatedDensityForFillingMaterials"] = value;
            }
        }
    }
}
